services:
  vidarr:
    build: .
    container_name: vidarr
    ports:
      - "3434:3434"
    volumes:
      - vidarr-config:/config
      - ./media:/media
    restart: unless-stopped

volumes:
  vidarr-config:
